# Generated by Django 5.1.7 on 2025-05-01 06:31

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('booking', '0002_booking_num_passengers_booking_price_and_more'),
    ]

    operations = [
        migrations.AddField(
            model_name='destination',
            name='is_international',
            field=models.BooleanField(default=False),
        ),
    ]
