# Generated by Django 5.1.7 on 2025-05-01 06:42

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('booking', '0003_destination_is_international'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='booking',
            name='booking_type',
        ),
        migrations.AddField(
            model_name='booking',
            name='mode_of_transport',
            field=models.CharField(choices=[('flight', 'Flight'), ('train', 'Train')], default='flight', max_length=10),
        ),
        migrations.AddField(
            model_name='booking',
            name='tour_type',
            field=models.CharField(choices=[('domestic', 'Domestic'), ('international', 'International')], default='domestic', max_length=20),
        ),
    ]
