# Generated by Django 5.1.7 on 2025-05-01 06:49

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('booking', '0004_remove_booking_booking_type_and_more'),
    ]

    operations = [
        migrations.AlterField(
            model_name='booking',
            name='mode_of_transport',
            field=models.CharField(blank=True, choices=[('flight', 'Flight'), ('train', 'Train')], max_length=10, null=True),
        ),
        migrations.AlterField(
            model_name='booking',
            name='tour_type',
            field=models.CharField(choices=[('domestic', 'Domestic'), ('international', 'International')], max_length=15),
        ),
    ]
