# Generated by Django 5.1.7 on 2025-05-01 15:19

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('booking', '0005_alter_booking_mode_of_transport_and_more'),
    ]

    operations = [
        migrations.AlterField(
            model_name='booking',
            name='destination',
            field=models.CharField(default='Unknown', max_length=100),
        ),
        migrations.DeleteModel(
            name='Flight',
        ),
        migrations.DeleteModel(
            name='Hotel',
        ),
        migrations.RenameField(
            model_name='booking',
            old_name='departure',
            new_name='airline',
        ),
        migrations.RenameField(
            model_name='booking',
            old_name='check_in',
            new_name='date_of_travel',
        ),
        migrations.RemoveField(
            model_name='booking',
            name='booking_date',
        ),
        migrations.RemoveField(
            model_name='booking',
            name='check_out',
        ),
        migrations.RemoveField(
            model_name='booking',
            name='hotel_name',
        ),
        migrations.RemoveField(
            model_name='booking',
            name='mode_of_transport',
        ),
        migrations.RemoveField(
            model_name='booking',
            name='num_passengers',
        ),
        migrations.RemoveField(
            model_name='booking',
            name='price',
        ),
        migrations.RemoveField(
            model_name='booking',
            name='special_requests',
        ),
        migrations.RemoveField(
            model_name='booking',
            name='travel_class',
        ),
        migrations.RemoveField(
            model_name='booking',
            name='user',
        ),
        migrations.AddField(
            model_name='booking',
            name='coach_type',
            field=models.CharField(blank=True, max_length=20, null=True),
        ),
        migrations.AddField(
            model_name='booking',
            name='flight_class',
            field=models.CharField(blank=True, choices=[('business', 'Business'), ('economy', 'Economy')], max_length=20, null=True),
        ),
        migrations.AddField(
            model_name='booking',
            name='flight_seat_no',
            field=models.CharField(blank=True, max_length=10, null=True),
        ),
        migrations.AddField(
            model_name='booking',
            name='hotel_booking',
            field=models.BooleanField(default=False),
        ),
        migrations.AddField(
            model_name='booking',
            name='hotel_star',
            field=models.CharField(blank=True, choices=[('5', '5 Star'), ('4', '4 Star'), ('3', '3 Star')], max_length=1, null=True),
        ),
        migrations.AddField(
            model_name='booking',
            name='mode_of_travel',
            field=models.CharField(choices=[('flight', 'Flight'), ('train', 'Train')], default='flight', max_length=10),
        ),
        migrations.AddField(
            model_name='booking',
            name='number_of_people',
            field=models.PositiveIntegerField(default=1),
        ),
        migrations.AddField(
            model_name='booking',
            name='train_class',
            field=models.CharField(blank=True, choices=[('ac', 'AC'), ('non-ac', 'Non-AC')], max_length=20, null=True),
        ),
        migrations.AddField(
            model_name='booking',
            name='train_number',
            field=models.CharField(blank=True, max_length=20, null=True),
        ),
        migrations.AddField(
            model_name='booking',
            name='train_seat_no',
            field=models.CharField(blank=True, max_length=10, null=True),
        ),
        migrations.AlterField(
            model_name='booking',
            name='flight_number',
            field=models.CharField(blank=True, max_length=20, null=True),
        ),
        migrations.AlterField(
            model_name='booking',
            name='room_type',
            field=models.CharField(blank=True, choices=[('single', 'Single'), ('double', 'Double'), ('suite', 'Suite')], max_length=10, null=True),
        ),
        migrations.AlterField(
            model_name='booking',
            name='tour_type',
            field=models.CharField(choices=[('domestic', 'Domestic'), ('international', 'International')], max_length=20),
        ),
        migrations.DeleteModel(
            name='Destination',
        ),
    ]
