# Generated by Django 5.1.7 on 2025-05-01 16:12

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('booking', '0006_alter_booking_destination_delete_flight_delete_hotel_and_more'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='booking',
            name='flight_number',
        ),
        migrations.RemoveField(
            model_name='booking',
            name='flight_seat_no',
        ),
    ]
