# Generated by Django 5.1.7 on 2025-05-01 17:55

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('booking', '0007_remove_booking_flight_number_and_more'),
    ]

    operations = [
        migrations.CreateModel(
            name='Destination',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(max_length=100)),
                ('tour_type', models.CharField(choices=[('domestic', 'Domestic'), ('international', 'International')], max_length=20)),
            ],
        ),
        migrations.CreateModel(
            name='TravelBooking',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('tour_type', models.CharField(choices=[('domestic', 'Domestic'), ('international', 'International')], max_length=20)),
                ('transport_mode', models.CharField(max_length=10)),
                ('hotel_category', models.CharField(choices=[('5star', '5 Star'), ('4star', '4 Star'), ('3star', '3 Star')], max_length=10)),
                ('num_people', models.PositiveIntegerField()),
                ('destination', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='booking.destination')),
            ],
        ),
        migrations.DeleteModel(
            name='Booking',
        ),
    ]
