# Generated by Django 5.1.7 on 2025-05-01 18:31

import datetime
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('booking', '0009_destination_country_destination_description_and_more'),
    ]

    operations = [
        migrations.AddField(
            model_name='travelbooking',
            name='travel_date',
            field=models.DateField(default=datetime.date.today),
        ),
    ]
