# Generated by Django 5.1.7 on 2025-05-02 07:47

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('booking', '0010_travelbooking_travel_date'),
    ]

    operations = [
        migrations.AddField(
            model_name='destination',
            name='duration',
            field=models.CharField(default=4, max_length=50),
        ),
        migrations.AddField(
            model_name='destination',
            name='places',
            field=models.TextField(default='unknown'),
        ),
        migrations.AddField(
            model_name='destination',
            name='price',
            field=models.DecimalField(decimal_places=2, default=10000, max_digits=8),
        ),
        migrations.AlterField(
            model_name='destination',
            name='description',
            field=models.TextField(),
        ),
    ]
