# Generated by Django 5.1.7 on 2025-05-03 07:37

import django.db.models.deletion
from django.conf import settings
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('booking', '0011_destination_duration_destination_places_and_more'),
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.AddField(
            model_name='travelbooking',
            name='user',
            field=models.ForeignKey(default=None, on_delete=django.db.models.deletion.CASCADE, to=settings.AUTH_USER_MODEL),
        ),
        migrations.AlterField(
            model_name='destination',
            name='description',
            field=models.TextField(default='No description available'),
        ),
        migrations.AlterField(
            model_name='destination',
            name='duration',
            field=models.CharField(default='4', max_length=50),
        ),
        migrations.AlterField(
            model_name='destination',
            name='places',
            field=models.TextField(default='Unknown'),
        ),
        migrations.CreateModel(
            name='Invoice',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('total_cost', models.DecimalField(decimal_places=2, max_digits=10)),
                ('invoice_date', models.DateField(auto_now_add=True)),
                ('pdf_file', models.FileField(blank=True, null=True, upload_to='invoices/')),
                ('booking', models.OneToOneField(on_delete=django.db.models.deletion.CASCADE, to='booking.travelbooking')),
            ],
        ),
    ]
