# Generated by Django 5.1.7 on 2025-05-04 17:43

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('booking', '0012_travelbooking_user_alter_destination_description_and_more'),
    ]

    operations = [
        migrations.AddField(
            model_name='travelbooking',
            name='total_cost',
            field=models.DecimalField(decimal_places=2, default=0.0, max_digits=10),
        ),
    ]
